### ISSUE TITLE
Could not load snapshot text (for buffer) — LSP functions not available

### ISSUE THREAD

**Issue by simlei** [scalameta/nvim-metals#415] opened 2022-06-19 07:48 UTC
### Describe the bug

Anyone else encountering these "Could not load snapshot text for [open file]"?

```txt
2022.06.19 09:28:42 WARN  Could not load snapshot text for /home/snuc/sandbox/bct/bci-logic/sub/graphs/src/main/scala-3/simlei/graphs/zcircuit/EdgeHandler.scala
```

I do constantly... This leads to
- diagnostics decoration still being displayed (properly)
- completion and hover etc. not working for that specific file

Setup:
- nvim-metals on `58ecfb61e4617139d3954138ccccc4c0befa89e0`
- neovim on `v0.8.0-dev+401-ge15d31b53` (local build with `LuaJIT 2.1.0-beta3`)
  - problem has been presented over >4 different versions over the last month
- only affects specific files like `EdgeHandler.scala` in this case, others are unaffected

here is the [metals]() and the [lsp]() log directly after...
- quitting neovim
- killing all java processes and making sure no process lingered
- restarting neovim and just opening `EdgeHandler.scala`
[metals.log](https://github.com/scalameta/nvim-metals/files/8934940/metals.log)
[lsp.trace.json](https://github.com/scalameta/nvim-metals/files/8934935/lsp.trace.json.log)

The error occurs sporadically and is hard to reproduce with a minimal example; I suspect the LSP hiccups somewhere inside my project but I can't tell even remotely why or how based on these logs.

### Expected behavior

The above described should not happen :)

### Operating system

Linux

### Version of Metals

0.11.6+69-e354275f-SNAPSHOT

### Commit of nvim-metals

58ecfb61e4617139d3954138ccccc4c0befa89e0

**Comment by ckipp01** [comment] 2022-06-22 08:17
Thanks for the report @simlei although it will be quite challenging to really dig into without some sort of reproduction. If I read the trace logs correctly, it seems that your project reports some diagnostics, and then you see that error message. This is sort of expected as that message about not being able to load up the semanticdb snapshots that Metals needs in order to offer code navigation. If the file isn't compiling and you're getting a bunch of diagnostics published, then semanticdb won't be able to be produced.

- When your file and project are compiling file, do you have any issues then?
- You mention this always happens `EdgeHandler.scala`, is this project public?

**Comment by simlei** [comment] 2022-06-22 09:51
Hi,

I feared this would not be sufficient information to really dig into it. That's ok. Though I don't yet fully understand what you're laying out with respect to semanticdb,  the error was too common for me to not take a stab at starting a public conversation where others could come in with their experience (or not- and it's just my particular project).

To answer your question: it's not just one particular file, but yes, it does seldom affect multiple files and even more uncommon, all of the scala files of the project. I will start tagging such files in git and maybe I'll get a "zoo" of these occurrences. Still, maybe, the problem will disappear completely at some point, probably a radical refactoring ^^

Is there a possibility of gathering additional log or ancillary days for the "zoo" that would help? E.g. semanticdb files?

**Comment by ckipp01** [comment] 2022-06-22 13:44
Hey @simlei, sorry if I wasn't super clear. I meant to sort of imply that I still don't fully understand exactly what the issue is in your case since some of the things you described are actually expected.

From reading through the original issue again you say

> completion and hover etc. not working for that specific file

Many times when stuff isn't compiling some of these features may not be working as expected. Without going into too much detail we typically have features that are powered by two different things in Metals

1. Presentation compiler - these are features that we use the actual Scala compiler for, the ones you mentioned are actually both powered by that: hover and completions.
2. SemanticDB - when you code gets compiled it produces semanticDB which Metals then can read up and use for navigation, references, workspace symbols. If your code can't compile it means it can't produce the semanticDB, which means these features won't really work.

So the message:

```
2022.06.19 09:28:42 WARN  Could not load snapshot text for /home/snuc/sandbox/bct/bci-logic/sub/graphs/src/main/scala-3/simlei/graphs/zcircuit/EdgeHandler.scala
```

Isn't really an error, but rather during that time, there is no semanticDB for that file.  That's why I asked if your project was compiling during this time, which could affect this. So in a fully working compiled workspace, does everything work as expected?

**Comment by ckipp01** [comment] 2022-08-11 17:57
Closing since I never got more info. If you're still hitting on this, feel free to report back.

**Closed by ckipp01** 2022-08-11 17:57 UTC
Labels: needs more info
