### ISSUE TITLE
MetalsNewFile: error in method "metals/quickPick"

### ISSUE THREAD

**Issue by mtjon** [scalameta/nvim-metals#217] opened 2021-09-14 15:09 UTC
**Describe the bug**

Attempting to create a new worksheet, in nvim I run `:MetalsNewScalaFile` and enter `6` in the prompt (this is the Worksheet option).
I get an error reported:
```
Error executing vim.schedule lua callback: ...nt_nvimHlwrLf/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:511: method
"metals/quickPick": either a result or an error must be sent to the server in response
```

**To Reproduce** Steps to reproduce the behavior:

1. Open a file in my current test project
2. Go to `build.sbt`
3. Ensure the build is imported
4. DO this `:MetalsNewScalaFile`
5. pick any option
6. See error

**Expected behavior**

A new worksheet is created.

**Installation:**

- Operating system: Linux
- Nvim version:  NVIM v0.6.0-dev+223-g384a43fe7
- Commit of nvim-metals: 954c6d4
- Metals version: metals 0.10.6

**Search terms**

MetalsNewScalaFile

**Comment by ckipp01** [comment] 2021-09-14 17:58
Thanks for the report @mtjon! I'm able to reproduce. It looks like this was introduced when I added the compat function to make the lsp handlers work for both the new handlers and the old ones 🤔 however it's not fully clear to my why this is a problem. I'll dig further into it.

**Comment by mtjon** [comment] 2021-09-14 20:13
You're welcome! I have no idea about the inner workings of nvim or its plugins 🤐 , but let me know if I can help by sharing additional info.

**Comment by ckipp01** [comment] 2021-09-14 20:28
So I see the issue, but don't fully understand it 😆 . I have a fix pushed up in a branch that I may hold off on merging since I don't fully understand why it's actually necessary. If this is a blocker for you, pull that branch and it will be fixed.

**Comment by mtjon** [comment] 2021-09-14 20:43
Not in a hurry to get that working, fortunately. Thanks for looking into it!

**Comment by ckipp01** [comment] 2021-09-14 20:43
I'm going to leave this open until I actually merge the fix 👍🏼

**Closed** 2021-09-15 05:16 UTC
Labels: bug
